# for version odler than 2.13.36
# package_name: mdl_release-{{ version }}.tar.gz
package_name: market_data_line-{{ version }}.tar.gz
package_url: http://artifactory.datayes.com/artifactory/mdl-release/com/datayes/market_data_line/{{ version }}/{{ package_name }}
install_items:
  - feeder_handler
  - libmdl_api.so
backup_items:
  - feeder_handler
  - feeder_handler.cfg
  - libmdl_api.so
  - version
put_files: []