- name: set backup dir
  set_fact: backup_dir={{ backups_dir }}/feeder_{{ existing_version }}_{{ ansible_date_time.iso8601_basic_short }}

- name: create backup dir
  file: path={{ backup_dir }} state=directory

- name: copy files
  copy: remote_src=yes src={{ install_dir }}/{{ item }} dest={{ backup_dir }}
  with_items: "{{ backup_items }}"
