- name: send consul-pull script
  template: src=templates/consul_pull.py.j2 dest={{ install_dir }}/consul_pull.py
  become: true

- name: consul pull
  shell: "{{ remote_python | default('/usr/bin/python') }} {{ install_dir }}/consul_pull.py"
  environment:
    CONSUL_TOKEN: "{{ consul_token }}"
  become: true
