- name: set backup dir
  set_fact: backup_dir={{ backups_dir }}/feeder_{{ existing_version }}_{{ ansible_date_time.iso8601_basic_short }}

- name: create backup dir
  file: path={{ backup_dir }} state=directory 

- name: move files
  command: mv {{ install_dir }}/{{ item }} {{ backup_dir }}
  with_items: "{{ backup_items }}"
