- name: stop service
  when: ansible_service_mgr == 'systemd'
  systemd: name={{ service_name }} state=stopped

- name: stop service
  when: ansible_service_mgr == 'upstart'
  service: name={{ service_name }} state=stopped


